### ISSUE TITLE
Call Rasa the app to get the answer

### ISSUE THREAD

**Issue by alexissmirnov** [dialoguemd/covid-19#271]
Please sync up with @lp-noel

**Comment by vicrep** [comment]
Re: discussion with LP

### COVID-FAQ
- Provide HTTP API, takes a `question`, Accept-Language header, returns `string[]` of answers

```
HTTP GET /get_answers?question={question_text}

200 OK:

{
  "answers": [ 
    "Don't cough on people", 
    "Don't have _playdates_", 
    "Here's the [source](google.com)"
  ]
}
```

### COVID-19 F/E
- ask for question
- query COVID-FAQ API
- render answers (if no answers, then show there's no answer, thank for question)
- ask if answers were pertinent "did that answer your question?"
- ask if another question
- loop or break
