### ISSUE TITLE
Add option to deactivate text field in chat window

### ISSUE THREAD

**Issue by NetBKarine** [dialoguemd/covid-19#756]
With the NLU additions we need buttons without text field and buttons with text field. The best would be an option that is necessary to deactivate it (should be activated by default) whether there are buttons or not. Something that could easily be added like this in the domain:
![image](https://user-images.githubusercontent.com/63261085/85167656-2c09b300-b237-11ea-8f03-f380ea7499d7.png)

**Comment by fparga** [comment]
Linked to dialoguemd/covidflow#344
